version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb_server
    environment:
      MONGO_INITDB_USERNAME: usuario
      MONGO_INITDB_PASSWORD: usuario1234
      MONGO_INITDB_DATABASE: platzi-store
    ports:
      - 27017:27017
    volumes:
      - ./mongo/:/etc/mongo

volumes:
  mongo: {}
